language: node_js

node_js:
  - '7'
  - '6'
  - '4'

before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

cache:
  yarn: true

before_deploy:
  - npm run minify

deploy:
  provider: npm
  email: avi.vahl@wix.com
  skip_cleanup: true
  api_key:
    secure: FWJ+Z8d9IBPjpGIN8euhFHKv+4FOXqksxEmdH1dPiMIaSyDOMZSOsoO90Nf+NaZpEdJWPqtHeyGRB8MlMS3OV+p8PbbhbuhQKJG4sOorbUigUfilMyUHlx1gwZcFLlXmTJcsvZRdHwt6pd/8JaESKq7EGJe9zto453Ae3Pkn2HukPdJTsStIgjK7rOOXpbTndY/u3osDvOU2CNjiCOMtSjkDH3zXD3IrDKynym+Tse9W9feYhW0frmSfVQZzkokZG427fC/ucn1W1+j1CEGVqW2RBSylyorzfCh5q49DEIsXzAf9JBRPrDfWgP6BjIjX1/AFTRPTJ1JiAiE6aHKsMcdZiTWTng//3zdIKl0Ur4AnnspHcYM7sKyKPxdAJWxyWCK8h4xq1eALHirnEeyOs47O/7MjNy9QXF2RQaH6nkWJ3Y45vFSNq51C3T4xcDB5SHiXOsPvLDZQPEbWHehn2+qRxSzktSXOT+Ouk4oZMQUc31DcwdsRdJDV2nhnczhYnV7yhAv2TeI8lutKDBt5jAKIJsSM15fc5VSbgutP84TrvtWf9h3k4jkFb9SbcpinyR6fM2ap9QGOsTgGmnCVPe7RUcMNhCT453IqvX61mpqyXOQILvSg6T69VNUVwbOJjjiBWbUb4SQ3OwvRukSZYMU1W5r01/AcrtO85BA4Wvc=
  on:
    tags: true
    repo: wix/vidi
    node: '6'
