export const MediaStreamTypes = {
    MP4: 'MP4',
    WEBM: 'WEBM',
    HLS: 'HLS',
    DASH: 'DASH'
}

/**
 * Represents a playable stream.
 * [[MediaStream]] objects are generated by a [[MediaSourceHandler]] and are later processed
 * in a [[MediaStreamHandler]]. 
 */
export interface MediaStream {
    /**
     * URL to the actual asset needed for playback
     * 
     * *Actual asset can be a `mp4` file, `m3u8` playlist, etc. *
     */
    url: string;

    /**
     * An identifier for the type of `MediaStream` being described.
     * Vidi has several built-in ones, exposed in [[Vidi.MediaStreamTypes]]
     * 
     * *For example: [[MediaStreamTypes.MP4]] or [[MediaStreamTypes.HLS]].*
     */
    type: string;

    /**
     * Additional data that the [[MediaSourceHandler]] might want to pass the [[MediaStreamHandler]].
     */
    [key: string]: any;
};
